# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.synced_folder ".", "/vagrant", disabled: false  
  config.vm.define "hdiotS" do |hdiotS|
    hdiotS.vm.hostname = "hdiotS"
    hdiotS.vm.network "private_network", ip: "192.168.56.110"
    hdiotS.vm.provider "virtualbox" do |vb|
      #vb.gui = "true"
      vb.name = "hdiotS"
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      #vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    hdiotS.vm.provision "shell", privileged: true, path: "/Users/lucasnaidu/Desktop/ecole42/Inceptionofthings/p2/scripts/script.sh"
  end
end