# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.synced_folder ".", "/vagrant", disabled: false  
  config.vm.define "eleleuxS" do |eleleuxS|
    eleleuxS.vm.hostname = "eleleuxS"
    eleleuxS.vm.network "private_network", ip: "192.168.56.110"
    eleleuxS.vm.provider "virtualbox" do |vb|
      vb.gui = "true"
      vb.name = "eleleuxS"
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      #vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    eleleuxS.vm.provision "shell", privileged: true, path: "/Users/lucasnaidu/Desktop/ecole42/Inceptionofthings/p1/script/scripts.sh"
  end

  config.vm.define "eleleuxSW" do |eleleuxSW|
    eleleuxSW.vm.hostname = "eleleuxSW"
    eleleuxSW.vm.network "private_network", ip: "192.168.56.111"
    eleleuxSW.vm.provider "virtualbox" do |vb|
      vb.gui = "true"
      vb.name = "eleleuxSW"
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      #vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    eleleuxSW.vm.provision "shell", privileged: true, path: "/Users/lucasnaidu/Desktop/ecole42/Inceptionofthings/p1/scripts/script.sh"
  end
end